Allowing to create questions without filling out body or tag field
answerdev/answer pull request #1188
Opened 2024-11-29 05:23 UTC by salimina

addressing issue #1177 and #842

2024-11-29 05:33 UTC, sy-records requested changes

2024-11-29 05:33 UTC, sy-records commented on ui/src/services/common.ts
> +}
Need add `;`

2024-11-29 05:33 UTC, sy-records commented on ui/src/services/common.ts
> +
Useless empty line

2024-11-29 05:33 UTC, sy-records commented on cmd/wire_gen.go
> -//go:build !wireinject
You need to revert this change.

2024-11-29 05:33 UTC, sy-records commented on data/conf/config.yaml
> +debug: false
No need to submit `data`

2024-11-29 05:33 UTC, sy-records commented on docs/docs.go
> -/*
The ASF header needs to be preserved.

2024-12-03 06:40 UTC, sosyz commented
Thank you for your contribution and addressing these two issues! 🎉 
I really appreciate your effort and would like to suggest a few minor improvements to help make this PR even better:

1. Code Organization:
   - Could you please squash your commits into a single, clean commit?
   - You can use `git squash` for this, followed by `git push -f` to update your repository
   - Pro tip: Consider backing up your code or trying this in a new branch first if you're new to squashing

2. Commit Message:
   - Let's enhance the commit message to better describe your changes
   - You can refer to other commits in our repository for the format
   - A good commit message helps other developers quickly understand the changes

3. Repository Cleanup:
   - The `data` directory contains runtime data files which shouldn't be tracked in Git
   - Please remove this directory from your commit
   - You can do this while squashing your commits

4. ASF Headers:
   - Please keep the original ASF headers unchanged
   - No need to include ASF header modifications in your commit

If you need any help with these changes or have questions, please don't hesitate to ask. I'm here to help! 😊

Thank you again for your contribution!

2026-05-08 12:07 UTC, LinkinStars commented
This has been going on for too long and there are some conflicts, so I'm closing this issue for now. If you have any further questions, please feel free to submit another one.

2026-05-08 12:07 UTC, closed without merging